project:
  type: website
  output-dir: ./docs

website:
  title: "Valeska Barbosa Alves"
  search: false

  # Header
  navbar:
    background: "#1B1F23"
    foreground: "#E8E8E8"
    pinned: true
    right: 
      - icon: github
        href: https://github.com/19872909
      - icon: linkedin 
        href: https://www.linkedin.com/in/valeskaalves/
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd

  # Foot
  page-footer:
    background: "#1B1F23"
    foreground: "#E8E8E8"
    center: "Copyright 2024" 
    border: true

  # Barra
  sidebar:
  - title: "Projects"
    style: "docked"
    border: true
    background: "#1B1F23"
    foreground: "#E8E8E8"
    contents:
      - projects.qmd
      - project1.qmd

  - title: "Reference teste"
    contents:
      - referece.qmd

format:
  html:
    html-math-method: katex
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    echo: true



